eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    register-with-eureka: false
    #表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    #fetch-registry: false
#  instance:
#    #实例名称
#    hostname: hostName
spring:
  application:
    name: eureka
  datasource:
    username: sysbase
    password: Epsoft2019
    url: jdbc:mysql://192.168.1.14/sysbase?jdbcCompliantTruncation=false&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080

#  jdbc.driver=com.mysql.jdbc.Driver
#  jdbc.url=jdbc:mysql://192.168.1.14/sysbase?jdbcCompliantTruncation=false&characterEncoding=UTF-8&allowMultiQueries=true
#  jdbc.user=sysbase
#  jdbc.pwd=Epsoft2019
#  jdbc.initialSize=5
#  jdbc.maxActive=20
